[package]
name = "big_fish_eat_small_fish"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.0"
egui = "0.27.0"
egui-chinese-font = "0.1"
fastrand = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
